### PR TITLE
Add support for Danish and German character sets

### PR DESCRIPTION
**Pull request by akien-mga**
If I did not miss something, this PR should add support to Danish and German "languages". The name is really misleading though, at first I thought perroquet only supported three languages, when it actually can create exercises for any language but might miss some characters. With the default English character set, I'm pretty sure that most languages using latin characters would be "supported".

Maybe you could change this "Language:" string to something like "Character set:"?

### CODE REVIEW

**Comment by niavok** [comment]
Thanks, i will merge that but i have a small question. I know almost nothing of german but i though there is "ß" character in this language ?

Yes, Perroquet is usable with exercice with "English" setting will work for all latin language but for exemple in french diacritic character are very frequent and a lot of character will be displayed in the new excercice making it easy.

Changing "Language:" to "Character set:" is a good idea. In fact i guess Perroquet will also need a automatic character conversion or a small virtual keyboard to resolve exercices in other latin languages. For exemple a english user will have difficulty to type some french character with a simple qwerty keyboard ...

**Comment by akien-mga** [comment]
> I know almost nothing of german but i though there is "ß" character in this language ?

That's correct, I'll add that :-D

> Changing "Language:" to "Character set:" is a good idea. In fact i guess Perroquet will also need a automatic character conversion or a small virtual keyboard to resolve exercices in other latin languages.

That sounds great. There might also be other things to handle in some languages, for example in German and Danish some special characters can be written as a pair of ascii letters, e.g.:
- ae, oe, ue, ss == ä, ö, ü, ß  in German
- ae, aa, oe == æ, å, ø  in Danish

Do you think the aliases list could be used for that? Does it works for subsets of words or only for full words?

**Comment by akien-mga** [comment]
I added ß in German, é and É in all languages since it's used in words imported from French and some missing accentuated characters in Spanish.

**Comment by niavok** [comment]
Do you have exemple of english word with é or É ? The problem is that if the user don't expect to have to type "é" he will not understand why Perroquet don't validate its word. If the é are very rare or only in foreigh surname like "Frédéric" it's maybe be less confusing to display theses character instead of let the user guess them.

I don't no if the aliases list actuallly work for this but it could be simple to add 2 alias categories : word aliases and character aliases.

**Comment by akien-mga** [comment]
There would be words like "fiancé(e)", "café", "cliché". But indeed such characters are relatively rare, and not always easy to input depending on the keyboard layout. It's also acceptable to write such words with a plain "e" AFAIK.

Actually to know what would be the best character set, I need to know how it is used by Perroquet: if a character is present in the character set (e.g. "é"), does that mean that it will have to be typed by the user, and that "e" won't work for example?
On the other hand, if it is not present in the character set, what will be the exercise if there is the word "café" in the subtitles? Will Perroquet "translate" the "é" to a normal "e", or will it display the "é" as if it was a punctuation character?

The best solution IMO would be that characters such as "é" that are relatively rare but still used in many words (one could probably expect to find at least one "é" in most film subtitles) would be part of the exercise but could be typed both as the actual diacritic character (é) or its ascii equivalent (e).
Maybe having most relevant characters in the character set + the official character aliases ("e" for "é", "ae" for "ä", etc.) could do the trick?

**Comment by niavok** [comment]
Yes, if a character is in the charset, the user will have to type the exact character. If not, the character is displayed as ponctuation.
Initially i write perroquet for me, to learn oral english. It create this charset features because some subititles files had sometimes japananeses word and its frustrating to try to type the right english word but it's impossible. The case of rare but valid character had never been seriously studied... 

In the case of the é for english, i'm agree that the character must be part of the exercice because the word can but find. I will try to add a character aliases features in nexts days.

So i merge your request. Thanks !

**Pull request merged**
